<?php echo $this->doctype(); ?>
<html>
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('Nutrifami')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
    ->appendName('viewport', 'width=device-width, initial-scale=1.0')
    ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
    ->prependStylesheet($this->basePath('css/style.css'))
    ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
    ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>
    <link href='https://fonts.googleapis.com/css?family=Raleway:400,700' rel='stylesheet' type='text/css'>
    <!-- Scripts -->
    <?php echo $this->headScript()
    ->prependFile($this->basePath('js/main.js'))
    ->prependFile($this->basePath('js/nutrifami.js'))
    ->prependFile($this->basePath('js/bootstrap.min.js'))
    ->prependFile($this->basePath('js/md5.js'))
    ->prependFile($this->basePath('js/jquery.min.js'))
    ->prependFile($this->basePath('js/service/services.js'))
    ->prependFile($this->basePath('js/service/perfilService.js'))
    ->prependFile($this->basePath('js/controller/loginController.js'))
    ->prependFile($this->basePath('js/controller/editarPerfilController.js'))
    ->prependFile($this->basePath('js/controller/perfilController.js'))
    ->prependFile($this->basePath('js/controller/homeController.js'))
    ->prependFile($this->basePath('js/mainController.js'))
    ->prependFile($this->basePath('js/angular-cookies.min.js'))
    ->prependFile($this->basePath('js/angular-route.min.js'))
    ->prependFile($this->basePath('lib/angular/angular.js'))
    ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9'))
    ->prependFile($this->basePath('js/html5shiv.min.js'), 'text/javascript', array('conditional' => 'lt IE 9'))
; ?>
</head>

<body ng-app="NutrifamiWeb">
    
            <ng-view>
                <?php echo $this->content; ?>
            </ng-view>

</body>
</html>
